# Generated by Django 4.1.7 on 2023-03-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Title', max_length=255),
            preserve_default=False,
        ),
    ]
