# Generated by Django 4.1.7 on 2023-03-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
