# Generated by Django 4.1.7 on 2023-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_pictures'),
        ),
    ]
